### ISSUE TITLE
Allow directory as DestinationPath in Grani_Download

### ISSUE THREAD

**Issue by hansmbakker** [guitarrapc/DSCResources#1]
It would be helpful to allow directories as DestinationPath in Grani_Download.

If GetPathItemType would return [GraniDonwloadItemTypeEx]::DirectoryInfo.ToString(), then you could internally append the fileName to the path.

**Comment by guitarrapc** [comment]
Hi @wind-rider 

Sorry for late response, this repository is obsolete and main repository moves to [GraniResource](https://github.com/guitarrapc/GraniResource). It's much appreciate if you can post issue from next.

It sounds nice but I also think "it probably better keep configuration as simple as possible". Passing Directory to the DestinationPath will required configuration reviewer to guess what the exactly file path when he want to debug. Passing file path is concrete and result to be simple. 

Also multiple same directory passing in configuration is same as cover by resource, just use `Join-Path` I think. What do you think?

``` powershell
configuration hoge
{
    Import-DscResource -ModuleName GraniResource;
    Node localhost
    {
        $dir = "C:\Tools";

        cDownload ReadMe
        {
            DestinationPath = Join-Path $dir "README.md"
            Uri = "https://raw.githubusercontent.com/guitarrapc/DSCResources/master/README.md"
        }

        cDownload Foo
        {
            DestinationPath = Join-Path $dir "Foo.txt"
            Uri = "https://raw.githubusercontent.com/guitarrapc/DSCResources/master/Foo.txt"
        }

        cDownload Bar
        {
            DestinationPath = Join-Path $dir "Bar.txt"
            Uri = "https://raw.githubusercontent.com/guitarrapc/DSCResources/master/Bar.txt"
        }
    }
}
```
