### ISSUE TITLE
[Breaking] GraniScheduledTask Action / Settings / Trigger will merged into CIMInstance

### ISSUE THREAD

**Issue by guitarrapc** [guitarrapc/DSCResources#46]
As there are vast options to be set in ScheduledTask, will merge keys into CIMInstance. Which means you can group parameters with HashTable from New-ScheduledTaskAction|Trigger|SettingsSet.

**Comment by renaudl** [comment]
Hey, do you plan to add management of public MSMQs to this wonderfull resource?

**Comment by guitarrapc** [comment]
What a idea:) It sounds very nice but no. As MSMQ is differ from core functionality of ScheduledTask it will not.

If I have any chance to use MSMQ, will create new MSMQ Resource but I don't. Therefore, there are not plan to add.
Cheers,

**Comment by guitarrapc** [comment]
This idea will be close, as there are another idea to brush up cTaskScheduler.

PowerShell ScheduledTasks Module is too poor to manage ScheduledTask. It is no good idea to rely on PowerShell bad system as there are too many limitation and no expose to extensibility.
